---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: "on"

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[databag_example::default]
    attributes:
